# Place this file in [repo]/.github/workflows/master.yml

on:
  push:
    branches:
      - master

name: ? Deploy website on push
jobs:
  web-deploy:
    name: ? Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ? Get latest code
        uses: actions/checkout@v2

      - name: ? Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          # InfinitiyFree FTP server
          server: ftpupload.net

          # add New repository secret "ftp_username" at repo / Settings / Secrets menu on Github
          username: ${{ secrets.ftp_username }}

          # add New repository secret "ftp_password" at repo / Settings / Secrets menu on Github
          password: ${{ secrets.ftp_password }}

          protocol: ftps
          server-dir: /htdocs/${{ github.event.repository.name }}/
